__author__ = 'student'
import random

choices = ["rock", "paper", "scissor"]
print "let's play a rock, paper, scissor game"


def game():
    tries = 0  # Holds value of player tries
    wins = 0  # Holds value of player wins
    """
    If certain conditions are met, print message.
    """
    while tries <= 5:
        if wins >= 3 and tries == 5:
            print "You won 3 game out of 5. You WIN!!!"
            exit()
        elif wins <= 3 and tries == 5:
            print "You lose MUHAHAHA!"
            exit()
        computer = random.randrange(0, 3)  # Generates random choice of rock, paper, scissor
        """
        Random number generated by computer variable is used as index number for choices list
        and it's assigned to computer_choice
        """
        computer_choice = choices[computer]
        print "Enter rock, paper or scissor"
        player_choice = str(raw_input(" > "))
        tries += 1  # Increments player tries by one to tries variable
        """
        If certain conditions are met, prints corresponding message.
        """
        if player_choice == computer_choice:
            print "it's tie!"

        elif player_choice == "rock" and computer_choice == choices[1]:
            print "It was " + computer_choice + "." + " You lose!"

        elif player_choice == "rock" and computer_choice == choices[2]:
            print "It was " + computer_choice + "." + " You win!"
            wins += 1  # Increments player wins by one to variable tries
        elif player_choice == "paper" and computer_choice == choices[0]:
            print "It was " + computer_choice + "." + " You win!"
            wins += 1  # Increments player wins by one to variable tries
        elif player_choice == "paper" and computer_choice == choices[2]:
            print "It was " + computer_choice + "." + " You lose!"

        elif player_choice == "scissor" and computer_choice == choices[0]:
            print "It was " + computer_choice + "." + " You lose!"

        elif player_choice == "scissor" and computer_choice == choices[1]:
            print "It was " + computer_choice + "." + " You win!"


game()  # Executes the game function 
